# Generated by Django 5.2.11 on 2026-02-13 21:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Valentine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        default=core.models.generate_uid,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("sender_name", models.CharField(max_length=50)),
                ("recipient_name", models.CharField(max_length=50)),
                ("acrostic_mode", models.CharField(default="default", max_length=10)),
                ("custom_acrostic", models.JSONField(blank=True, null=True)),
                ("poem_mode", models.CharField(default="default", max_length=10)),
                ("custom_poem", models.TextField(blank=True, null=True)),
                ("music_mode", models.CharField(default="default", max_length=10)),
                ("youtube_id", models.CharField(blank=True, max_length=20, null=True)),
                ("sender_ip", models.GenericIPAddressField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
